export const TECH_STACK = [
  { name: 'React', category: 'frontend' },
  { name: 'Next.js', category: 'frontend' },
  { name: 'TypeScript', category: 'frontend' },
  { name: 'Python', category: 'backend' },
  { name: 'FastAPI', category: 'backend' },
  { name: 'Node.js', category: 'backend' },
  { name: 'Go', category: 'backend' },
  { name: 'Java', category: 'backend' },
  { name: '.NET', category: 'backend' },
  { name: 'Flutter', category: 'mobile' },
  { name: 'AWS', category: 'cloud' },
  { name: 'Azure', category: 'cloud' },
  { name: 'Docker', category: 'devops' },
  { name: 'Kubernetes', category: 'devops' },
  { name: 'Redis', category: 'data' },
  { name: 'PostgreSQL', category: 'data' },
  { name: 'MongoDB', category: 'data' },
  { name: 'Kafka', category: 'data' },
  { name: 'OpenAI', category: 'ai' },
  { name: 'Claude', category: 'ai' },
  { name: 'Gemini', category: 'ai' },
  { name: 'LangChain', category: 'ai' },
  { name: 'n8n', category: 'ai' },
] as const
